# Generated by Django 6.1.1 on 2026-10-03 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mypurchase',
            fields=[
                ('Product_name', models.CharField(max_length=15)),
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField()),
                ('Offer', models.FloatField()),
                ('Weight', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Total_amount', models.IntegerField()),
            ],
        ),
    ]
